- id: '1624922335660'
  alias: Включить свет
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 8c3dac0ad22d1e3fac79d62c256cdc2f
    type: action
    subtype: single
    discovery_id: 0x00158d00045a78f9 action_single
  condition: []
  action:
  - type: turn_on
    device_id: f573cd89b0f68350b54b15a7c1526c71
    entity_id: switch.0x04cf8cdf3c77e630
    domain: switch
  mode: single
- id: '1624922622002'
  alias: Выключить свет
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 8c3dac0ad22d1e3fac79d62c256cdc2f
    type: action
    subtype: single
    discovery_id: 0x00158d00045a78f9 action_single
  condition: []
  action:
  - type: turn_off
    device_id: f573cd89b0f68350b54b15a7c1526c71
    entity_id: switch.0x04cf8cdf3c77e630
    domain: switch
  mode: single
- id: '1625148486539'
  alias: on_off_switch
  description: ''
  trigger: []
  condition: []
  action:
  - type: toggle
    device_id: f573cd89b0f68350b54b15a7c1526c71
    entity_id: switch.0x04cf8cdf3c77e630
    domain: switch
  mode: single
