# инфо о системе
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_temperature
    - type: ipv4_address
      arg: eth0
    - type: processor_use
    - type: last_boot

- platform: sql
  db_url: !secret db_link
  queries:
    - name: maria_db
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1048576, 2) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: 'value'
      unit_of_measurement: MB

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'

- platform: uptime
  name: online

- platform: template
  sensors:
      online_custom:
        friendly_name: "Home Assistant в онлайне"
        value_template: >
            {% set uptime = as_timestamp (now()) -as_timestamp(states('sensor.online')) | int %}
            {% set minutes = (( uptime % 3600) / 60) | int %}
            {% set hours = ((uptime % 86400) / 3600) | int %}
            {% set days = (uptime / 86400) | int %}
             {% if uptime < 1 %}
               Меньше минуты
             {% else %}
               {% if days > 0 %}
                 {{ days }} д.
               {% endif %}
               {% if hours > 0 %}
                 {% if days > 0 %}
                   {{ ' ' }}
                 {% endif %}
                 {{ hours }} ч.
               {% endif %}
               {% if minutes > 0 %}
                 {% if days > 0 or hours > 0 %}
                   {{ ' ' }}
                 {% endif %}
                   {{ minutes }} мин.
               {% endif %}
             {% endif %}
        icon_template: mdi:clock
      # Время с последней перезагрузки
      last_boot_custom:
        friendly_name: "Сервер в онлайне"
        value_template: >
           {% set uptime = as_timestamp (now()) -as_timestamp(states('sensor.last_boot')) | int %}
           {% set minutes = (( uptime % 3600) / 60) | int %}
           {% set hours = ((uptime % 86400) / 3600) | int %}
           {% set days = (uptime / 86400) | int %}
             {% if uptime < 1 %}
               Меньше минуты
             {% else %}
               {% if days > 0 %}
                 {{ days }} д.
               {% endif %}
               {% if hours > 0 %}
                 {% if days > 0 %}
                   {{ ' ' }}
                 {% endif %}
                 {{ hours }} ч.
               {% endif %}
               {% if minutes > 0 %}
                 {% if days > 0 or hours > 0 %}
                   {{ ' ' }}
                 {% endif %}
                   {{ minutes }} мин.
               {% endif %}
             {% endif %}
        icon_template: mdi:clock